### ISSUE TITLE
one pod, 2 pvc end 2 pv not working

### ISSUE THREAD

**Issue by promzeus** [wunderio/csi-rclone#16]
hi,
Create one pod, 2 pvc end 2 pv 
```
---
# Source: duckdice/templates/pv-pvc-data.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: release-name-data
  labels:
    name: release-name-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  storageClassName: "rclone"
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remotePath: "cluster-dev/release-name-data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-data
spec:
  storageClassName: "rclone"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: release-name-data
---
# Source: duckdice/templates/pv-pvc-reports.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: release-name-reports
  labels:
    name: release-name-reports
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  storageClassName: "rclone"
  csi:
    driver: csi-rclone
    volumeHandle: data-id
    volumeAttributes:
      remotePath: "cluster-dev/release-name-reports"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-reports
spec:
  storageClassName: "rclone"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      name: release-name-reports
```
end deployment 
```
        volumeMounts:
        - mountPath: /var/www/storage/app/public
          name: release-name-data
        - mountPath: /var/www/storage/app/user_reports
          name: release-name-reports
        resources:
            {}
      volumes:
      - name: release-name-data
        persistentVolumeClaim:
          claimName: release-name-data
      - name: release-name-reports
        persistentVolumeClaim:
          claimName: release-name-reports
```
not working!!!
