### ISSUE TITLE
StorageClass shouldn't be namespaced

### ISSUE THREAD

**Issue by mkjmdski** [wunderio/csi-rclone#26]
By Kubernetes API design StorageClass shouldn't be namespaced as it will be accessible for any namespace anyway.

I propose to switch to file like one proposed below if there are no reasons to do otherwise

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rclone
provisioner: kubernetes.io/no-provisioner
```
