### ISSUE TITLE
Not mounting

### ISSUE THREAD

**Issue by 0xEmma** [wunderio/csi-rclone#43]
Tried setting this up on K3S, using the rancher.io/local-path provisioner, PVC will bind without issue to the Rclone Storage class, however the PVC is not infact backed by rclone.

(defaults are setup in the secret)
SC Config: 
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app.kubernetes.io/instance: rclone-csi
  name: rclone
provisioner: csi-rclone
```
PVC Config:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rclone-example
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rclone
  ```
